import { logInfo } from '@hubspot/cms-components';
import React, { useEffect, useState } from 'react';
import weatherStyles from '../../styles/weather.module.css';
const sampleData = {
  location: {
    name: 'Dallas',
    region: 'Texas',
    country: 'United States of America',
    lat: 32.78,
    lon: -96.8,
    tz_id: 'America/Chicago',
    localtime_epoch: 1717771638,
    localtime: '2024-06-07 9:47',
  },
  current: {
    last_updated_epoch: 1717771500,
    last_updated: '2024-06-07 09:45',
    temp_c: 28.3,
    temp_f: 82.9,
    is_day: 1,
    condition: {
      text: 'Partly cloudy',
      icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
      code: 1003,
    },
    wind_mph: 5.6,
    wind_kph: 9.0,
    wind_degree: 180,
    wind_dir: 'S',
    pressure_mb: 1015.0,
    pressure_in: 29.96,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 57,
    cloud: 25,
    feelslike_c: 30.0,
    feelslike_f: 85.9,
    windchill_c: 26.3,
    windchill_f: 79.4,
    heatindex_c: 27.5,
    heatindex_f: 81.5,
    dewpoint_c: 17.2,
    dewpoint_f: 62.9,
    vis_km: 16.0,
    vis_miles: 9.0,
    uv: 7.0,
    gust_mph: 5.8,
    gust_kph: 9.3,
  },
  forecast: {
    forecastday: [
      {
        date: '2024-06-07',
        date_epoch: 1717718400,
        day: {
          maxtemp_c: 33.8,
          maxtemp_f: 92.8,
          mintemp_c: 23.0,
          mintemp_f: 73.3,
          avgtemp_c: 28.2,
          avgtemp_f: 82.7,
          maxwind_mph: 11.2,
          maxwind_kph: 18.0,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 57,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000,
          },
          uv: 11.0,
        },
        astro: {
          sunrise: '06:19 AM',
          sunset: '08:34 PM',
          moonrise: '06:59 AM',
          moonset: '10:16 PM',
          moon_phase: 'Waxing Crescent',
          moon_illumination: 0,
          is_moon_up: 1,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1717736400,
            time: '2024-06-07 00:00',
            temp_c: 26.0,
            temp_f: 78.9,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 152,
            wind_dir: 'SSE',
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 65,
            cloud: 2,
            feelslike_c: 27.5,
            feelslike_f: 81.5,
            windchill_c: 26.0,
            windchill_f: 78.9,
            heatindex_c: 27.5,
            heatindex_f: 81.5,
            dewpoint_c: 18.7,
            dewpoint_f: 65.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.0,
            uv: 1.0,
          },
          {
            time_epoch: 1717740000,
            time: '2024-06-07 01:00',
            temp_c: 25.5,
            temp_f: 77.8,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 163,
            wind_dir: 'SSE',
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 66,
            cloud: 4,
            feelslike_c: 26.9,
            feelslike_f: 80.5,
            windchill_c: 25.5,
            windchill_f: 77.8,
            heatindex_c: 26.9,
            heatindex_f: 80.5,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
            uv: 1.0,
          },
          {
            time_epoch: 1717743600,
            time: '2024-06-07 02:00',
            temp_c: 24.9,
            temp_f: 76.9,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 168,
            wind_dir: 'SSE',
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 67,
            cloud: 4,
            feelslike_c: 26.4,
            feelslike_f: 79.6,
            windchill_c: 24.9,
            windchill_f: 76.9,
            heatindex_c: 26.4,
            heatindex_f: 79.6,
            dewpoint_c: 18.3,
            dewpoint_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
            uv: 1.0,
          },
          {
            time_epoch: 1717747200,
            time: '2024-06-07 03:00',
            temp_c: 24.4,
            temp_f: 76.0,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 165,
            wind_dir: 'SSE',
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 67,
            cloud: 6,
            feelslike_c: 26.0,
            feelslike_f: 78.8,
            windchill_c: 24.4,
            windchill_f: 76.0,
            heatindex_c: 26.0,
            heatindex_f: 78.8,
            dewpoint_c: 17.8,
            dewpoint_f: 64.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.6,
            gust_kph: 17.1,
            uv: 1.0,
          },
          {
            time_epoch: 1717750800,
            time: '2024-06-07 04:00',
            temp_c: 23.9,
            temp_f: 75.1,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 170,
            wind_dir: 'S',
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 66,
            cloud: 8,
            feelslike_c: 25.6,
            feelslike_f: 78.1,
            windchill_c: 23.9,
            windchill_f: 75.1,
            heatindex_c: 25.6,
            heatindex_f: 78.1,
            dewpoint_c: 17.3,
            dewpoint_f: 63.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.5,
            gust_kph: 15.2,
            uv: 1.0,
          },
          {
            time_epoch: 1717754400,
            time: '2024-06-07 05:00',
            temp_c: 23.5,
            temp_f: 74.3,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 172,
            wind_dir: 'S',
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 66,
            cloud: 5,
            feelslike_c: 25.3,
            feelslike_f: 77.6,
            windchill_c: 23.5,
            windchill_f: 74.3,
            heatindex_c: 25.3,
            heatindex_f: 77.6,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 13.9,
            uv: 1.0,
          },
          {
            time_epoch: 1717758000,
            time: '2024-06-07 06:00',
            temp_c: 23.2,
            temp_f: 73.8,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 160,
            wind_dir: 'SSE',
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 66,
            cloud: 7,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.2,
            windchill_f: 73.8,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 16.3,
            dewpoint_f: 61.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.1,
            gust_kph: 16.3,
            uv: 1.0,
          },
          {
            time_epoch: 1717761600,
            time: '2024-06-07 07:00',
            temp_c: 23.8,
            temp_f: 74.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 158,
            wind_dir: 'SSE',
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 67,
            cloud: 8,
            feelslike_c: 25.5,
            feelslike_f: 77.9,
            windchill_c: 23.8,
            windchill_f: 74.9,
            heatindex_c: 25.5,
            heatindex_f: 77.9,
            dewpoint_c: 16.6,
            dewpoint_f: 61.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.8,
            gust_kph: 14.1,
            uv: 6.0,
          },
          {
            time_epoch: 1717765200,
            time: '2024-06-07 08:00',
            temp_c: 25.0,
            temp_f: 76.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 157,
            wind_dir: 'SSE',
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 63,
            cloud: 8,
            feelslike_c: 26.3,
            feelslike_f: 79.4,
            windchill_c: 25.0,
            windchill_f: 76.9,
            heatindex_c: 26.3,
            heatindex_f: 79.4,
            dewpoint_c: 17.0,
            dewpoint_f: 62.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.7,
            uv: 6.0,
          },
          {
            time_epoch: 1717768800,
            time: '2024-06-07 09:00',
            temp_c: 28.3,
            temp_f: 82.9,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 180,
            wind_dir: 'S',
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 57,
            cloud: 25,
            feelslike_c: 27.5,
            feelslike_f: 81.5,
            windchill_c: 26.3,
            windchill_f: 79.4,
            heatindex_c: 27.5,
            heatindex_f: 81.5,
            dewpoint_c: 17.2,
            dewpoint_f: 62.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 16.0,
            vis_miles: 9.0,
            gust_mph: 5.8,
            gust_kph: 9.3,
            uv: 7.0,
          },
          {
            time_epoch: 1717772400,
            time: '2024-06-07 10:00',
            temp_c: 27.7,
            temp_f: 81.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 143,
            wind_dir: 'SE',
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 54,
            cloud: 8,
            feelslike_c: 28.9,
            feelslike_f: 84.1,
            windchill_c: 27.7,
            windchill_f: 81.9,
            heatindex_c: 28.9,
            heatindex_f: 84.1,
            dewpoint_c: 17.5,
            dewpoint_f: 63.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.4,
            gust_kph: 10.4,
            uv: 7.0,
          },
          {
            time_epoch: 1717776000,
            time: '2024-06-07 11:00',
            temp_c: 29.1,
            temp_f: 84.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 156,
            wind_dir: 'SSE',
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 51,
            cloud: 9,
            feelslike_c: 30.4,
            feelslike_f: 86.7,
            windchill_c: 29.1,
            windchill_f: 84.3,
            heatindex_c: 30.4,
            heatindex_f: 86.7,
            dewpoint_c: 18.0,
            dewpoint_f: 64.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.5,
            gust_kph: 12.0,
            uv: 7.0,
          },
          {
            time_epoch: 1717779600,
            time: '2024-06-07 12:00',
            temp_c: 30.5,
            temp_f: 86.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 162,
            wind_dir: 'SSE',
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 48,
            cloud: 7,
            feelslike_c: 32.0,
            feelslike_f: 89.6,
            windchill_c: 30.5,
            windchill_f: 86.9,
            heatindex_c: 32.0,
            heatindex_f: 89.6,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.0,
            gust_kph: 12.9,
            uv: 8.0,
          },
          {
            time_epoch: 1717783200,
            time: '2024-06-07 13:00',
            temp_c: 31.7,
            temp_f: 89.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 164,
            wind_dir: 'SSE',
            pressure_mb: 1014.0,
            pressure_in: 29.95,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 44,
            cloud: 5,
            feelslike_c: 33.4,
            feelslike_f: 92.0,
            windchill_c: 31.7,
            windchill_f: 89.1,
            heatindex_c: 33.4,
            heatindex_f: 92.0,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 8.0,
          },
          {
            time_epoch: 1717786800,
            time: '2024-06-07 14:00',
            temp_c: 32.6,
            temp_f: 90.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 164,
            wind_dir: 'SSE',
            pressure_mb: 1013.0,
            pressure_in: 29.93,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 42,
            cloud: 4,
            feelslike_c: 34.4,
            feelslike_f: 93.9,
            windchill_c: 32.6,
            windchill_f: 90.7,
            heatindex_c: 34.4,
            heatindex_f: 93.9,
            dewpoint_c: 18.3,
            dewpoint_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.6,
            gust_kph: 17.0,
            uv: 8.0,
          },
          {
            time_epoch: 1717790400,
            time: '2024-06-07 15:00',
            temp_c: 33.2,
            temp_f: 91.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 169,
            wind_dir: 'S',
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 41,
            cloud: 4,
            feelslike_c: 35.1,
            feelslike_f: 95.1,
            windchill_c: 33.2,
            windchill_f: 91.7,
            heatindex_c: 35.1,
            heatindex_f: 95.1,
            dewpoint_c: 18.3,
            dewpoint_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.3,
            gust_kph: 18.2,
            uv: 8.0,
          },
          {
            time_epoch: 1717794000,
            time: '2024-06-07 16:00',
            temp_c: 33.4,
            temp_f: 92.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 171,
            wind_dir: 'S',
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 40,
            cloud: 4,
            feelslike_c: 35.4,
            feelslike_f: 95.7,
            windchill_c: 33.4,
            windchill_f: 92.1,
            heatindex_c: 35.4,
            heatindex_f: 95.7,
            dewpoint_c: 18.3,
            dewpoint_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.1,
            gust_kph: 19.5,
            uv: 8.0,
          },
          {
            time_epoch: 1717797600,
            time: '2024-06-07 17:00',
            temp_c: 33.1,
            temp_f: 91.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 171,
            wind_dir: 'S',
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 41,
            cloud: 3,
            feelslike_c: 35.2,
            feelslike_f: 95.4,
            windchill_c: 33.1,
            windchill_f: 91.7,
            heatindex_c: 35.2,
            heatindex_f: 95.4,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.6,
            gust_kph: 20.3,
            uv: 8.0,
          },
          {
            time_epoch: 1717801200,
            time: '2024-06-07 18:00',
            temp_c: 32.5,
            temp_f: 90.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 170,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 44,
            cloud: 3,
            feelslike_c: 34.9,
            feelslike_f: 94.9,
            windchill_c: 32.5,
            windchill_f: 90.5,
            heatindex_c: 34.9,
            heatindex_f: 94.9,
            dewpoint_c: 18.9,
            dewpoint_f: 66.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.5,
            uv: 8.0,
          },
          {
            time_epoch: 1717804800,
            time: '2024-06-07 19:00',
            temp_c: 31.3,
            temp_f: 88.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 168,
            wind_dir: 'SSE',
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 50,
            cloud: 3,
            feelslike_c: 33.9,
            feelslike_f: 93.0,
            windchill_c: 31.3,
            windchill_f: 88.3,
            heatindex_c: 33.9,
            heatindex_f: 93.0,
            dewpoint_c: 20.2,
            dewpoint_f: 68.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 8.0,
          },
          {
            time_epoch: 1717808400,
            time: '2024-06-07 20:00',
            temp_c: 30.0,
            temp_f: 85.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 166,
            wind_dir: 'SSE',
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 58,
            cloud: 3,
            feelslike_c: 32.6,
            feelslike_f: 90.6,
            windchill_c: 30.0,
            windchill_f: 85.9,
            heatindex_c: 32.6,
            heatindex_f: 90.6,
            dewpoint_c: 21.0,
            dewpoint_f: 69.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.6,
            gust_kph: 25.1,
            uv: 8.0,
          },
          {
            time_epoch: 1717812000,
            time: '2024-06-07 21:00',
            temp_c: 28.9,
            temp_f: 84.1,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 168,
            wind_dir: 'SSE',
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 64,
            cloud: 2,
            feelslike_c: 31.5,
            feelslike_f: 88.6,
            windchill_c: 28.9,
            windchill_f: 84.1,
            heatindex_c: 31.5,
            heatindex_f: 88.6,
            dewpoint_c: 21.2,
            dewpoint_f: 70.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.8,
            gust_kph: 27.1,
            uv: 1.0,
          },
          {
            time_epoch: 1717815600,
            time: '2024-06-07 22:00',
            temp_c: 28.2,
            temp_f: 82.8,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 168,
            wind_dir: 'SSE',
            pressure_mb: 1009.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 67,
            cloud: 2,
            feelslike_c: 30.6,
            feelslike_f: 87.1,
            windchill_c: 28.2,
            windchill_f: 82.8,
            heatindex_c: 30.6,
            heatindex_f: 87.1,
            dewpoint_c: 21.2,
            dewpoint_f: 70.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.7,
            gust_kph: 28.5,
            uv: 1.0,
          },
          {
            time_epoch: 1717819200,
            time: '2024-06-07 23:00',
            temp_c: 27.6,
            temp_f: 81.7,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 176,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 67,
            cloud: 2,
            feelslike_c: 29.9,
            feelslike_f: 85.7,
            windchill_c: 27.6,
            windchill_f: 81.7,
            heatindex_c: 29.9,
            heatindex_f: 85.7,
            dewpoint_c: 20.9,
            dewpoint_f: 69.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.2,
            gust_kph: 27.8,
            uv: 1.0,
          },
        ],
      },
      {
        date: '2024-06-08',
        date_epoch: 1717804800,
        day: {
          maxtemp_c: 34.3,
          maxtemp_f: 93.7,
          mintemp_c: 24.8,
          mintemp_f: 76.6,
          avgtemp_c: 29.3,
          avgtemp_f: 84.7,
          maxwind_mph: 14.8,
          maxwind_kph: 23.8,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 58,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000,
          },
          uv: 11.0,
        },
        astro: {
          sunrise: '06:18 AM',
          sunset: '08:34 PM',
          moonrise: '08:00 AM',
          moonset: '11:07 PM',
          moon_phase: 'Waxing Crescent',
          moon_illumination: 3,
          is_moon_up: 1,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1717822800,
            time: '2024-06-08 00:00',
            temp_c: 27.1,
            temp_f: 80.7,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 179,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 68,
            cloud: 3,
            feelslike_c: 29.2,
            feelslike_f: 84.5,
            windchill_c: 27.1,
            windchill_f: 80.7,
            heatindex_c: 29.2,
            heatindex_f: 84.5,
            dewpoint_c: 20.7,
            dewpoint_f: 69.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.9,
            gust_kph: 20.8,
            uv: 1.0,
          },
          {
            time_epoch: 1717826400,
            time: '2024-06-08 01:00',
            temp_c: 26.5,
            temp_f: 79.6,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 159,
            wind_dir: 'SSE',
            pressure_mb: 1011.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 70,
            cloud: 3,
            feelslike_c: 28.5,
            feelslike_f: 83.3,
            windchill_c: 26.5,
            windchill_f: 79.6,
            heatindex_c: 28.5,
            heatindex_f: 83.3,
            dewpoint_c: 20.7,
            dewpoint_f: 69.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.1,
            uv: 1.0,
          },
          {
            time_epoch: 1717830000,
            time: '2024-06-08 02:00',
            temp_c: 26.0,
            temp_f: 78.9,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 163,
            wind_dir: 'SSE',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 73,
            cloud: 4,
            feelslike_c: 27.9,
            feelslike_f: 82.3,
            windchill_c: 26.0,
            windchill_f: 78.9,
            heatindex_c: 27.9,
            heatindex_f: 82.3,
            dewpoint_c: 20.6,
            dewpoint_f: 69.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
            uv: 1.0,
          },
          {
            time_epoch: 1717833600,
            time: '2024-06-08 03:00',
            temp_c: 25.6,
            temp_f: 78.1,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 182,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 72,
            cloud: 3,
            feelslike_c: 27.4,
            feelslike_f: 81.4,
            windchill_c: 25.6,
            windchill_f: 78.1,
            heatindex_c: 27.4,
            heatindex_f: 81.4,
            dewpoint_c: 20.1,
            dewpoint_f: 68.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.5,
            gust_kph: 24.9,
            uv: 1.0,
          },
          {
            time_epoch: 1717837200,
            time: '2024-06-08 04:00',
            temp_c: 25.4,
            temp_f: 77.7,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 177,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 72,
            cloud: 4,
            feelslike_c: 27.1,
            feelslike_f: 80.8,
            windchill_c: 25.4,
            windchill_f: 77.6,
            heatindex_c: 27.1,
            heatindex_f: 80.8,
            dewpoint_c: 19.8,
            dewpoint_f: 67.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.8,
            gust_kph: 25.4,
            uv: 1.0,
          },
          {
            time_epoch: 1717840800,
            time: '2024-06-08 05:00',
            temp_c: 25.1,
            temp_f: 77.1,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 190,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 71,
            cloud: 4,
            feelslike_c: 26.7,
            feelslike_f: 80.1,
            windchill_c: 25.1,
            windchill_f: 77.1,
            heatindex_c: 26.7,
            heatindex_f: 80.1,
            dewpoint_c: 19.4,
            dewpoint_f: 66.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1.0,
          },
          {
            time_epoch: 1717844400,
            time: '2024-06-08 06:00',
            temp_c: 24.9,
            temp_f: 76.9,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 193,
            wind_dir: 'SSW',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 71,
            cloud: 4,
            feelslike_c: 26.6,
            feelslike_f: 79.9,
            windchill_c: 24.9,
            windchill_f: 76.9,
            heatindex_c: 26.6,
            heatindex_f: 79.9,
            dewpoint_c: 19.1,
            dewpoint_f: 66.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 1.0,
          },
          {
            time_epoch: 1717848000,
            time: '2024-06-08 07:00',
            temp_c: 25.4,
            temp_f: 77.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 187,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 71,
            cloud: 4,
            feelslike_c: 27.0,
            feelslike_f: 80.7,
            windchill_c: 25.4,
            windchill_f: 77.7,
            heatindex_c: 27.0,
            heatindex_f: 80.7,
            dewpoint_c: 19.3,
            dewpoint_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.5,
            gust_kph: 26.6,
            uv: 6.0,
          },
          {
            time_epoch: 1717851600,
            time: '2024-06-08 08:00',
            temp_c: 26.4,
            temp_f: 79.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 192,
            wind_dir: 'SSW',
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 67,
            cloud: 4,
            feelslike_c: 27.9,
            feelslike_f: 82.2,
            windchill_c: 26.4,
            windchill_f: 79.5,
            heatindex_c: 27.9,
            heatindex_f: 82.2,
            dewpoint_c: 19.3,
            dewpoint_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.7,
            uv: 7.0,
          },
          {
            time_epoch: 1717855200,
            time: '2024-06-08 09:00',
            temp_c: 27.8,
            temp_f: 82.0,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 196,
            wind_dir: 'SSW',
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 58,
            cloud: 4,
            feelslike_c: 29.1,
            feelslike_f: 84.3,
            windchill_c: 27.8,
            windchill_f: 82.0,
            heatindex_c: 29.1,
            heatindex_f: 84.3,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.6,
            gust_kph: 26.7,
            uv: 7.0,
          },
          {
            time_epoch: 1717858800,
            time: '2024-06-08 10:00',
            temp_c: 29.2,
            temp_f: 84.6,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 14.3,
            wind_kph: 23.0,
            wind_degree: 199,
            wind_dir: 'SSW',
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 51,
            cloud: 4,
            feelslike_c: 30.5,
            feelslike_f: 86.9,
            windchill_c: 29.2,
            windchill_f: 84.6,
            heatindex_c: 30.5,
            heatindex_f: 86.9,
            dewpoint_c: 17.8,
            dewpoint_f: 64.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.8,
            gust_kph: 27.1,
            uv: 7.0,
          },
          {
            time_epoch: 1717862400,
            time: '2024-06-08 11:00',
            temp_c: 30.6,
            temp_f: 87.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 14.1,
            wind_kph: 22.7,
            wind_degree: 196,
            wind_dir: 'SSW',
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 46,
            cloud: 4,
            feelslike_c: 31.9,
            feelslike_f: 89.5,
            windchill_c: 30.6,
            windchill_f: 87.1,
            heatindex_c: 31.9,
            heatindex_f: 89.5,
            dewpoint_c: 17.7,
            dewpoint_f: 63.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.2,
            gust_kph: 26.1,
            uv: 8.0,
          },
          {
            time_epoch: 1717866000,
            time: '2024-06-08 12:00',
            temp_c: 31.8,
            temp_f: 89.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 14.3,
            wind_kph: 23.0,
            wind_degree: 193,
            wind_dir: 'SSW',
            pressure_mb: 1011.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 43,
            cloud: 3,
            feelslike_c: 33.3,
            feelslike_f: 91.9,
            windchill_c: 31.8,
            windchill_f: 89.2,
            heatindex_c: 33.3,
            heatindex_f: 91.9,
            dewpoint_c: 17.7,
            dewpoint_f: 63.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.5,
            gust_kph: 26.5,
            uv: 8.0,
          },
          {
            time_epoch: 1717869600,
            time: '2024-06-08 13:00',
            temp_c: 32.7,
            temp_f: 90.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 14.5,
            wind_kph: 23.4,
            wind_degree: 193,
            wind_dir: 'SSW',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 41,
            cloud: 3,
            feelslike_c: 34.5,
            feelslike_f: 94.1,
            windchill_c: 32.7,
            windchill_f: 90.9,
            heatindex_c: 34.5,
            heatindex_f: 94.1,
            dewpoint_c: 18.0,
            dewpoint_f: 64.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.7,
            gust_kph: 26.9,
            uv: 8.0,
          },
          {
            time_epoch: 1717873200,
            time: '2024-06-08 14:00',
            temp_c: 33.4,
            temp_f: 92.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 190,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 40,
            cloud: 2,
            feelslike_c: 35.5,
            feelslike_f: 95.9,
            windchill_c: 33.4,
            windchill_f: 92.2,
            heatindex_c: 35.5,
            heatindex_f: 95.9,
            dewpoint_c: 18.4,
            dewpoint_f: 65.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.0,
            gust_kph: 27.3,
            uv: 8.0,
          },
          {
            time_epoch: 1717876800,
            time: '2024-06-08 15:00',
            temp_c: 33.9,
            temp_f: 92.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 190,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 40,
            cloud: 2,
            feelslike_c: 36.2,
            feelslike_f: 97.2,
            windchill_c: 33.9,
            windchill_f: 92.9,
            heatindex_c: 36.2,
            heatindex_f: 97.2,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.0,
            gust_kph: 27.3,
            uv: 8.0,
          },
          {
            time_epoch: 1717880400,
            time: '2024-06-08 16:00',
            temp_c: 34.0,
            temp_f: 93.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 14.5,
            wind_kph: 23.4,
            wind_degree: 193,
            wind_dir: 'SSW',
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 41,
            cloud: 2,
            feelslike_c: 36.6,
            feelslike_f: 97.9,
            windchill_c: 34.0,
            windchill_f: 93.1,
            heatindex_c: 36.6,
            heatindex_f: 97.9,
            dewpoint_c: 19.1,
            dewpoint_f: 66.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.7,
            gust_kph: 26.9,
            uv: 8.0,
          },
          {
            time_epoch: 1717884000,
            time: '2024-06-08 17:00',
            temp_c: 33.7,
            temp_f: 92.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 14.1,
            wind_kph: 22.7,
            wind_degree: 191,
            wind_dir: 'SSW',
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 43,
            cloud: 0,
            feelslike_c: 36.6,
            feelslike_f: 98.0,
            windchill_c: 33.7,
            windchill_f: 92.7,
            heatindex_c: 36.6,
            heatindex_f: 98.0,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.2,
            gust_kph: 26.1,
            uv: 8.0,
          },
          {
            time_epoch: 1717887600,
            time: '2024-06-08 18:00',
            temp_c: 33.1,
            temp_f: 91.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 185,
            wind_dir: 'S',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 46,
            cloud: 0,
            feelslike_c: 36.4,
            feelslike_f: 97.4,
            windchill_c: 33.1,
            windchill_f: 91.5,
            heatindex_c: 36.4,
            heatindex_f: 97.4,
            dewpoint_c: 20.3,
            dewpoint_f: 68.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.8,
            uv: 8.0,
          },
          {
            time_epoch: 1717891200,
            time: '2024-06-08 19:00',
            temp_c: 31.9,
            temp_f: 89.4,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 177,
            wind_dir: 'S',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 51,
            cloud: 0,
            feelslike_c: 35.4,
            feelslike_f: 95.6,
            windchill_c: 31.9,
            windchill_f: 89.4,
            heatindex_c: 35.4,
            heatindex_f: 95.6,
            dewpoint_c: 21.2,
            dewpoint_f: 70.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.9,
            gust_kph: 23.9,
            uv: 8.0,
          },
          {
            time_epoch: 1717894800,
            time: '2024-06-08 20:00',
            temp_c: 30.6,
            temp_f: 87.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 168,
            wind_dir: 'SSE',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 60,
            cloud: 0,
            feelslike_c: 34.0,
            feelslike_f: 93.3,
            windchill_c: 30.6,
            windchill_f: 87.1,
            heatindex_c: 34.0,
            heatindex_f: 93.3,
            dewpoint_c: 22.0,
            dewpoint_f: 71.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.1,
            gust_kph: 24.4,
            uv: 8.0,
          },
          {
            time_epoch: 1717898400,
            time: '2024-06-08 21:00',
            temp_c: 29.7,
            temp_f: 85.4,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 165,
            wind_dir: 'SSE',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 65,
            cloud: 0,
            feelslike_c: 32.9,
            feelslike_f: 91.2,
            windchill_c: 29.7,
            windchill_f: 85.4,
            heatindex_c: 32.9,
            heatindex_f: 91.2,
            dewpoint_c: 22.1,
            dewpoint_f: 71.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.6,
            gust_kph: 26.7,
            uv: 1.0,
          },
          {
            time_epoch: 1717902000,
            time: '2024-06-08 22:00',
            temp_c: 28.9,
            temp_f: 84.1,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 167,
            wind_dir: 'SSE',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 66,
            cloud: 0,
            feelslike_c: 31.9,
            feelslike_f: 89.4,
            windchill_c: 28.9,
            windchill_f: 84.1,
            heatindex_c: 31.9,
            heatindex_f: 89.4,
            dewpoint_c: 21.8,
            dewpoint_f: 71.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.0,
            gust_kph: 27.4,
            uv: 1.0,
          },
          {
            time_epoch: 1717905600,
            time: '2024-06-08 23:00',
            temp_c: 28.3,
            temp_f: 82.9,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 166,
            wind_dir: 'SSE',
            pressure_mb: 1009.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 68,
            cloud: 21,
            feelslike_c: 31.1,
            feelslike_f: 88.0,
            windchill_c: 28.3,
            windchill_f: 82.9,
            heatindex_c: 31.1,
            heatindex_f: 88.0,
            dewpoint_c: 21.7,
            dewpoint_f: 71.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.4,
            gust_kph: 28.1,
            uv: 1.0,
          },
        ],
      },
      {
        date: '2024-06-09',
        date_epoch: 1717891200,
        day: {
          maxtemp_c: 34.0,
          maxtemp_f: 93.1,
          mintemp_c: 23.3,
          mintemp_f: 73.9,
          avgtemp_c: 28.7,
          avgtemp_f: 83.7,
          maxwind_mph: 13.2,
          maxwind_kph: 21.2,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 61,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000,
          },
          uv: 11.0,
        },
        astro: {
          sunrise: '06:18 AM',
          sunset: '08:35 PM',
          moonrise: '09:03 AM',
          moonset: '11:50 PM',
          moon_phase: 'Waxing Crescent',
          moon_illumination: 7,
          is_moon_up: 1,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1717909200,
            time: '2024-06-09 00:00',
            temp_c: 27.8,
            temp_f: 82.0,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 172,
            wind_dir: 'S',
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 70,
            cloud: 21,
            feelslike_c: 30.3,
            feelslike_f: 86.6,
            windchill_c: 27.7,
            windchill_f: 81.9,
            heatindex_c: 30.3,
            heatindex_f: 86.6,
            dewpoint_c: 21.7,
            dewpoint_f: 71.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.5,
            gust_kph: 29.8,
            uv: 1.0,
          },
          {
            time_epoch: 1717912800,
            time: '2024-06-09 01:00',
            temp_c: 27.1,
            temp_f: 80.7,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 178,
            wind_dir: 'S',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 70,
            cloud: 5,
            feelslike_c: 29.3,
            feelslike_f: 84.7,
            windchill_c: 27.1,
            windchill_f: 80.7,
            heatindex_c: 29.3,
            heatindex_f: 84.7,
            dewpoint_c: 21.2,
            dewpoint_f: 70.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.5,
            gust_kph: 31.3,
            uv: 1.0,
          },
          {
            time_epoch: 1717916400,
            time: '2024-06-09 02:00',
            temp_c: 26.4,
            temp_f: 79.5,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 180,
            wind_dir: 'S',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 69,
            cloud: 0,
            feelslike_c: 28.3,
            feelslike_f: 83.0,
            windchill_c: 26.4,
            windchill_f: 79.5,
            heatindex_c: 28.3,
            heatindex_f: 83.0,
            dewpoint_c: 20.3,
            dewpoint_f: 68.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.5,
            gust_kph: 31.4,
            uv: 1.0,
          },
          {
            time_epoch: 1717920000,
            time: '2024-06-09 03:00',
            temp_c: 25.7,
            temp_f: 78.3,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 179,
            wind_dir: 'S',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 69,
            cloud: 0,
            feelslike_c: 27.5,
            feelslike_f: 81.5,
            windchill_c: 25.7,
            windchill_f: 78.3,
            heatindex_c: 27.5,
            heatindex_f: 81.5,
            dewpoint_c: 19.6,
            dewpoint_f: 67.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.3,
            gust_kph: 31.0,
            uv: 1.0,
          },
          {
            time_epoch: 1717923600,
            time: '2024-06-09 04:00',
            temp_c: 25.0,
            temp_f: 77.0,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 189,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 71,
            cloud: 0,
            feelslike_c: 26.8,
            feelslike_f: 80.2,
            windchill_c: 25.0,
            windchill_f: 77.0,
            heatindex_c: 26.8,
            heatindex_f: 80.2,
            dewpoint_c: 19.3,
            dewpoint_f: 66.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 1.0,
          },
          {
            time_epoch: 1717927200,
            time: '2024-06-09 05:00',
            temp_c: 24.3,
            temp_f: 75.7,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 187,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 74,
            cloud: 0,
            feelslike_c: 26.1,
            feelslike_f: 79.0,
            windchill_c: 24.3,
            windchill_f: 75.7,
            heatindex_c: 26.1,
            heatindex_f: 79.0,
            dewpoint_c: 19.4,
            dewpoint_f: 67.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.6,
            uv: 1.0,
          },
          {
            time_epoch: 1717930800,
            time: '2024-06-09 06:00',
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 176,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 78,
            cloud: 0,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 19.5,
            dewpoint_f: 67.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 1.0,
          },
          {
            time_epoch: 1717934400,
            time: '2024-06-09 07:00',
            temp_c: 24.0,
            temp_f: 75.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 182,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 80,
            cloud: 1,
            feelslike_c: 25.9,
            feelslike_f: 78.6,
            windchill_c: 24.0,
            windchill_f: 75.2,
            heatindex_c: 25.9,
            heatindex_f: 78.6,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.6,
            gust_kph: 20.3,
            uv: 6.0,
          },
          {
            time_epoch: 1717938000,
            time: '2024-06-09 08:00',
            temp_c: 24.9,
            temp_f: 76.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 181,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 77,
            cloud: 0,
            feelslike_c: 26.7,
            feelslike_f: 80.1,
            windchill_c: 24.9,
            windchill_f: 76.8,
            heatindex_c: 26.7,
            heatindex_f: 80.1,
            dewpoint_c: 19.9,
            dewpoint_f: 67.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.0,
            gust_kph: 22.5,
            uv: 6.0,
          },
          {
            time_epoch: 1717941600,
            time: '2024-06-09 09:00',
            temp_c: 26.3,
            temp_f: 79.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 183,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 71,
            cloud: 3,
            feelslike_c: 28.2,
            feelslike_f: 82.7,
            windchill_c: 26.3,
            windchill_f: 79.3,
            heatindex_c: 28.2,
            heatindex_f: 82.7,
            dewpoint_c: 20.1,
            dewpoint_f: 68.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.0,
            gust_kph: 20.8,
            uv: 7.0,
          },
          {
            time_epoch: 1717945200,
            time: '2024-06-09 10:00',
            temp_c: 27.9,
            temp_f: 82.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 13.2,
            wind_kph: 21.2,
            wind_degree: 191,
            wind_dir: 'SSW',
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 64,
            cloud: 2,
            feelslike_c: 29.9,
            feelslike_f: 85.9,
            windchill_c: 27.9,
            windchill_f: 82.2,
            heatindex_c: 29.9,
            heatindex_f: 85.9,
            dewpoint_c: 20.2,
            dewpoint_f: 68.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.2,
            gust_kph: 24.4,
            uv: 7.0,
          },
          {
            time_epoch: 1717948800,
            time: '2024-06-09 11:00',
            temp_c: 29.5,
            temp_f: 85.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 188,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 56,
            cloud: 2,
            feelslike_c: 31.6,
            feelslike_f: 88.8,
            windchill_c: 29.5,
            windchill_f: 85.1,
            heatindex_c: 31.6,
            heatindex_f: 88.8,
            dewpoint_c: 19.8,
            dewpoint_f: 67.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.6,
            gust_kph: 22.0,
            uv: 7.0,
          },
          {
            time_epoch: 1717952400,
            time: '2024-06-09 12:00',
            temp_c: 30.9,
            temp_f: 87.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 184,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 50,
            cloud: 13,
            feelslike_c: 33.0,
            feelslike_f: 91.4,
            windchill_c: 30.9,
            windchill_f: 87.5,
            heatindex_c: 33.0,
            heatindex_f: 91.4,
            dewpoint_c: 19.4,
            dewpoint_f: 67.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.7,
            gust_kph: 23.6,
            uv: 8.0,
          },
          {
            time_epoch: 1717956000,
            time: '2024-06-09 13:00',
            temp_c: 32.0,
            temp_f: 89.6,
            is_day: 1,
            condition: {
              text: 'Partly Cloudy ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 185,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 46,
            cloud: 49,
            feelslike_c: 34.2,
            feelslike_f: 93.6,
            windchill_c: 32.0,
            windchill_f: 89.6,
            heatindex_c: 34.2,
            heatindex_f: 93.6,
            dewpoint_c: 19.1,
            dewpoint_f: 66.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.5,
            uv: 8.0,
          },
          {
            time_epoch: 1717959600,
            time: '2024-06-09 14:00',
            temp_c: 32.8,
            temp_f: 91.1,
            is_day: 1,
            condition: {
              text: 'Partly Cloudy ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 181,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 43,
            cloud: 35,
            feelslike_c: 35.0,
            feelslike_f: 95.0,
            windchill_c: 32.8,
            windchill_f: 91.1,
            heatindex_c: 35.0,
            heatindex_f: 95.0,
            dewpoint_c: 18.9,
            dewpoint_f: 66.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.3,
            gust_kph: 19.9,
            uv: 8.0,
          },
          {
            time_epoch: 1717963200,
            time: '2024-06-09 15:00',
            temp_c: 33.4,
            temp_f: 92.1,
            is_day: 1,
            condition: {
              text: 'Partly Cloudy ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 177,
            wind_dir: 'S',
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 41,
            cloud: 32,
            feelslike_c: 35.6,
            feelslike_f: 96.1,
            windchill_c: 33.4,
            windchill_f: 92.1,
            heatindex_c: 35.6,
            heatindex_f: 96.1,
            dewpoint_c: 18.6,
            dewpoint_f: 65.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.8,
            gust_kph: 19.0,
            uv: 8.0,
          },
          {
            time_epoch: 1717966800,
            time: '2024-06-09 16:00',
            temp_c: 33.6,
            temp_f: 92.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 172,
            wind_dir: 'S',
            pressure_mb: 1008.0,
            pressure_in: 29.78,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 40,
            cloud: 0,
            feelslike_c: 35.9,
            feelslike_f: 96.6,
            windchill_c: 33.6,
            windchill_f: 92.5,
            heatindex_c: 35.9,
            heatindex_f: 96.6,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.8,
            gust_kph: 19.0,
            uv: 8.0,
          },
          {
            time_epoch: 1717970400,
            time: '2024-06-09 17:00',
            temp_c: 33.5,
            temp_f: 92.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 169,
            wind_dir: 'S',
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 41,
            cloud: 3,
            feelslike_c: 35.8,
            feelslike_f: 96.4,
            windchill_c: 33.5,
            windchill_f: 92.2,
            heatindex_c: 35.8,
            heatindex_f: 96.4,
            dewpoint_c: 18.7,
            dewpoint_f: 65.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.6,
            uv: 8.0,
          },
          {
            time_epoch: 1717974000,
            time: '2024-06-09 18:00',
            temp_c: 32.9,
            temp_f: 91.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 166,
            wind_dir: 'SSE',
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 43,
            cloud: 12,
            feelslike_c: 35.3,
            feelslike_f: 95.5,
            windchill_c: 32.9,
            windchill_f: 91.1,
            heatindex_c: 35.3,
            heatindex_f: 95.5,
            dewpoint_c: 19.1,
            dewpoint_f: 66.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.1,
            gust_kph: 17.8,
            uv: 8.0,
          },
          {
            time_epoch: 1717977600,
            time: '2024-06-09 19:00',
            temp_c: 31.9,
            temp_f: 89.4,
            is_day: 1,
            condition: {
              text: 'Partly Cloudy ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 162,
            wind_dir: 'SSE',
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 47,
            cloud: 37,
            feelslike_c: 34.6,
            feelslike_f: 94.2,
            windchill_c: 31.9,
            windchill_f: 89.4,
            heatindex_c: 34.6,
            heatindex_f: 94.2,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.2,
            gust_kph: 19.6,
            uv: 8.0,
          },
          {
            time_epoch: 1717981200,
            time: '2024-06-09 20:00',
            temp_c: 30.5,
            temp_f: 86.9,
            is_day: 1,
            condition: {
              text: 'Partly Cloudy ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 156,
            wind_dir: 'SSE',
            pressure_mb: 1007.0,
            pressure_in: 29.74,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 55,
            cloud: 32,
            feelslike_c: 33.4,
            feelslike_f: 92.1,
            windchill_c: 30.5,
            windchill_f: 86.9,
            heatindex_c: 33.4,
            heatindex_f: 92.1,
            dewpoint_c: 20.9,
            dewpoint_f: 69.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.0,
            gust_kph: 21.0,
            uv: 8.0,
          },
          {
            time_epoch: 1717984800,
            time: '2024-06-09 21:00',
            temp_c: 29.3,
            temp_f: 84.8,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 157,
            wind_dir: 'SSE',
            pressure_mb: 1007.0,
            pressure_in: 29.74,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 65,
            cloud: 4,
            feelslike_c: 32.2,
            feelslike_f: 89.9,
            windchill_c: 29.3,
            windchill_f: 84.8,
            heatindex_c: 32.2,
            heatindex_f: 89.9,
            dewpoint_c: 21.9,
            dewpoint_f: 71.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.3,
            gust_kph: 24.7,
            uv: 1.0,
          },
          {
            time_epoch: 1717988400,
            time: '2024-06-09 22:00',
            temp_c: 28.4,
            temp_f: 83.1,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 156,
            wind_dir: 'SSE',
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 68,
            cloud: 2,
            feelslike_c: 31.0,
            feelslike_f: 87.9,
            windchill_c: 28.4,
            windchill_f: 83.1,
            heatindex_c: 31.0,
            heatindex_f: 87.9,
            dewpoint_c: 21.6,
            dewpoint_f: 70.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.6,
            gust_kph: 17.1,
            uv: 1.0,
          },
          {
            time_epoch: 1717992000,
            time: '2024-06-09 23:00',
            temp_c: 27.5,
            temp_f: 81.5,
            is_day: 0,
            condition: {
              text: 'Clear ',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 150,
            wind_dir: 'SSE',
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 70,
            cloud: 0,
            feelslike_c: 30.0,
            feelslike_f: 86.0,
            windchill_c: 27.5,
            windchill_f: 81.5,
            heatindex_c: 30.0,
            heatindex_f: 86.0,
            dewpoint_c: 21.5,
            dewpoint_f: 70.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.0,
            gust_kph: 16.1,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};

const baseApiUrl = 'https://weatherapi-com.p.rapidapi.com/forecast.json';
const options = {
  method: 'GET',
  headers: {
    'x-rapidapi-key': '20c6efc89fmshc5028f84c47f8a1p19a4a7jsnf3fead1e08a5',
    'x-rapidapi-host': 'weatherapi-com.p.rapidapi.com',
  },
};

async function getWeatherForecast(city: string) {
  try {
    const response = await fetch(`${baseApiUrl}?q=${city}&days=5`, options);
    const result = await response.text();
    return result;
  } catch (error) {
    console.error(error);
  }
}

export function CurrentWeatherCard({ weather }) {
  return (
    <div className={weatherStyles.current}>
      <sup>{weather.date}</sup>
      <h3>{weather.day.avgtemp_f} degrees</h3>
    </div>
  );
}

export function WeatherCard({ weather }) {
  return (
    <div className={weatherStyles.card}>
      <sup>{weather.date}</sup>
      <h3>{weather.day.avgtemp_f} degrees</h3>
    </div>
  );
}

export default function WeatherForecast(props: { headline: string }) {
  const [city, setCity] = useState('');
  const [forecast, setForecast] = useState([] as any);

  const handleFetchWeather = () => {
    // getWeatherForecast(city).then((data) => {
    //   const { forecast } = JSON.parse(data);
    //   setForecast(forecast);
    //   logInfo('Weather forecast fetched');
    // });
  };

  return (
    <div className={weatherStyles.wrapper}>
      <h2>{props.headline}</h2>
      <div className={weatherStyles.form}>
        <input
          type="text"
          placeholder="Enter city"
          onChange={(event) => setCity(event.target.value)}
        />
        <button onClick={handleFetchWeather}>Update Forecast</button>
      </div>
      <div className={weatherStyles.currentWeather}>
        <CurrentWeatherCard
          key={sampleData.forecast.forecastday[0].date}
          weather={sampleData.forecast.forecastday[0]}
        />
      </div>
      <div className={weatherStyles.cardContainer}>
        {sampleData.forecast.forecastday.map((weather: any, i) => {
          if (i === 0) return null;
          return <WeatherCard key={weather.date} weather={weather} />;
        })}
      </div>
    </div>
  );
}
